############################################################################################
# Pest Control Application Configuration
#
# This file overrides the application configuration properties, mainly in providing a list of
# available CockroachDB clusters for users to pick from at login time.
# The credentials are used to retrieve Cluster API session tokens and provide bearer tokens in
# case of CockroachDB cloud (Cloud API).
# The cluster type is used to adapt security settings and certain UI features.
#
# For the application properties this file overrides, see: src/resources/application.yml.
# For all other spring boot container properties, see:
# https://docs.spring.io/spring-boot/appendix/application-properties/index.html
############################################################################################

## Truststore for SSL/TLS access to secure clusters
# Uncomment the section below if you intend to sign in to a secure, self-hosted CockroachDB cluster.
# The truststore is created with the 'cluster-admin certs' command.

#spring:
#  ssl:
#    bundle:
#      jks:
#        pestcontrol:
#          truststore:
#            location: "file:.certs/pestcontrol.p12"
#            password: "cockroach"
#            type: "PKCS12"

## HTTP server parameters
#server:
#  port: 9090

## List of all available CockroachDB clusters
#
#     cluster-id: Either a CockroachDB cloud cluster ID any name for other cluster types
#  cluster-type: cloud_dedicated, local_secure or local_insecure
#       api-key: Only required for cloud_dedicated, see https://www.cockroachlabs.com/docs/cockroachcloud/managing-access#create-api-keys
#     admin-url: Base URL for the Cluster API, typically the regional/local cluster load balancer endpoint.
#  data-source-properties:
#           url: The JDBC connection url
#      username: The SQL user name with ADMIN role
#      password: The SQL user password
application:
  # Examples below
  clusters:
    - cluster-id: "97a73235-fa45-4b4d-a229-f5efd52168ba"
      cluster-type: cloud_dedicated
      api-key: "<private-key>"
      admin-url: "https://admin-odin-qzx.cockroachlabs.cloud:8080"
      data-source-properties:
        url: "jdbc:postgresql://odin-qzx.aws-eu-north-1.cockroachlabs.cloud:26257/defaultdb?sslmode=require"
        username: "craig"
        password: "cockroach"

    - cluster-id: "Local Secure Cluster"
      cluster-type: local_secure
      admin-url: "https://localhost:443"
      data-source-properties:
        url: "jdbc:postgresql://localhost:26257/defaultdb?sslmode=require"
        username: "craig"
        password: "cockroach"

    - cluster-id: "Local Insecure Cluster"
      cluster-type: local_insecure
      admin-url: "http://localhost:8080"
      data-source-properties:
        url: "jdbc:postgresql://localhost:26257/defaultdb?sslmode=disable"
        username: "craig"
        password: ""